# Numpy: Statistiques, mathématiques et algèbre linéaire

URL : https://youtu.be/RwFiNlL4Q8g?si=bAYbSq3Cw9Imc70t

In [178]:
import numpy as np

In [179]:
#Pour que les valeurs ne changent pas
#si on veut changer les éléments de A, on change le 0
np.random.seed(0)

#A est un tableau de dimensions (2,3), càd 2 lignes et 3 colonnes
# et qui a des valeurs int compris entre 0 et 10
A = np.random.randint(0, 10, [2,3])

#afficher A
A

array([[5, 0, 3],
       [3, 7, 9]])

## Méthodes basiques nd.array

### La somme: sum()

In [182]:
#afficher A
A

array([[5, 0, 3],
       [3, 7, 9]])

In [183]:
#la somme de tous les éléments du tableau
A.sum()

27

In [184]:
#la somme de tous les éléments du tableau, pour axis=0 (l'axe vertical)
A.sum(axis=0)

array([ 8,  7, 12])

In [185]:
#la somme de tous les éléments du tableau, pour axis=1 (l'axe horizontal)
A.sum(axis=1)

array([ 8, 19])

### La somme cumulée: cumsum()

In [187]:
#afficher A
A

array([[5, 0, 3],
       [3, 7, 9]])

In [188]:
#la somme cumulée de tous les éléments du tableau
A.cumsum()

array([ 5,  5,  8, 11, 18, 27])

In [189]:
#la somme cumulée de tous les éléments du tableau, pour axis=0 (l'axe vertical)
A.cumsum(axis=0)

array([[ 5,  0,  3],
       [ 8,  7, 12]])

In [190]:
#la somme cumulée de tous les éléments du tableau, pour axis=1 (l'axe horizontal)
A.cumsum(axis=1)

array([[ 5,  5,  8],
       [ 3, 10, 19]])

### Le produit, le produit cumulé: prod(), cumprod()

In [192]:
#afficher A
A

array([[5, 0, 3],
       [3, 7, 9]])

In [193]:
#le produit de tous les éléments du tableau A
A.prod()

0

In [194]:
#le produit cumulé de tous les éléments du tableau A
A.cumprod()

array([5, 0, 0, 0, 0, 0])

### Le minimum, le maximum: min(), max()

#### La valeur minimale: min()

In [197]:
#afficher A
A

array([[5, 0, 3],
       [3, 7, 9]])

In [198]:
#Le minimum du tableau A
A.min()

0

In [199]:
#Le minimum du tableau A pour axis=0
A.min(axis=0)

array([3, 0, 3])

#### La position de la valeur minimale: argmin()

In [201]:
#la position du minimum dans le tableau A
A.argmin()

1

In [202]:
#la position du minimum dans le tableau A selon axis=0
A.argmin(axis=0)

array([1, 0, 0], dtype=int64)

In [203]:
'''
Le minimum du tableau A pour axis=0 est:
array([3, 0, 3])

3 occupe l'indexe 1 dans l'axis=0, dans la 1ere colonne
0 occupe l'indexe 0 dans l'axis=0, dans la 2eme colonne
3 occupe l'indexe 0 dans l'axis=0, dans la 3eme colonne
'''

"\nLe minimum du tableau A pour axis=0 est:\narray([3, 0, 3])\n\n3 occupe l'indexe 1 dans l'axis=0, dans la 1ere colonne\n0 occupe l'indexe 0 dans l'axis=0, dans la 2eme colonne\n3 occupe l'indexe 0 dans l'axis=0, dans la 3eme colonne\n"

**Remarque:**

Comme il y a les methodes **min() et argmin()**, il y a les methodes **max() et argmax()**. On peut les appliquer de la meme maniere.

### sort() et argsort()

#### sort()

In [207]:
#tableau B
B = np.array([[1,4], [7,5]])

#afficher B
B

array([[1, 4],
       [7, 5]])

In [208]:
#ordonner selon axis=0
B.sort(axis=0)

#afficher B
B

array([[1, 4],
       [7, 5]])

In [209]:
#ordonner selon axis=1
B.sort(axis=1)

#afficher B
B

array([[1, 4],
       [5, 7]])

#### argsort()

- Tableau a 1 dimension:

In [212]:
#tableau C avec 1 dimension
C = np.array([3, 1, 2])

#afficher C
C

array([3, 1, 2])

In [213]:
#la façon dont il faut trier les indexes du + petit au + grand
np.argsort(C)

array([1, 2, 0], dtype=int64)

In [214]:
# 1 < 2 < 3
#indexe 1, indexe 2, indexe 0

- Tableau a 2 dimensions:

In [216]:
#tableau D avec 2 dimensions
D = np.array([[0, 3], [2, 2]])
D

array([[0, 3],
       [2, 2]])

In [217]:
#ordonner le tableau selon axis=0
np.argsort(D, axis=0)

array([[0, 1],
       [1, 0]], dtype=int64)

In [218]:
#pour la 1ère colonne
# 0 < 2
# l'indexe de 0 est 0, l'indexe de 2 est 1

#pour la 2ème colonne
# 2 < 3
# l'indexe de 2 est 1, l'indexe de 3 est 0

In [219]:
#ordonner le tableau selon axis=1
np.argsort(D, axis=1)

array([[0, 1],
       [0, 1]], dtype=int64)

In [220]:
#pour la 1ère ligne
# 0 < 3
# l'indexe de 0 est: 0, l'indexe de 3 est: 1

#pour la 2ème ligne
# 2 =< 2
# l'indexe de 2 est: 0, l'indexe de 2 est: 1

### exp(), log(), cos(), sin()

In [222]:
#afficher B
B

array([[1, 4],
       [5, 7]])

In [223]:
np.exp(B)

array([[   2.71828183,   54.59815003],
       [ 148.4131591 , 1096.63315843]])

In [224]:
np.log(B)

array([[0.        , 1.38629436],
       [1.60943791, 1.94591015]])

In [225]:
np.cos(B)

array([[ 0.54030231, -0.65364362],
       [ 0.28366219,  0.75390225]])

In [226]:
np.sin(B)

array([[ 0.84147098, -0.7568025 ],
       [-0.95892427,  0.6569866 ]])

In [227]:
np.sinh(B)

array([[  1.17520119,  27.2899172 ],
       [ 74.20321058, 548.31612327]])

# Statistiques

### mean()

In [230]:
#afficher A
A

array([[5, 0, 3],
       [3, 7, 9]])

In [231]:
#moyenne du tableau A
A.mean()

4.5

In [232]:
#moyenne du tableau A selon axis=0
A.mean(axis=0)

array([4. , 3.5, 6. ])

In [233]:
#moyenne du tableau A selon axis=1
A.mean(axis=1)

array([2.66666667, 6.33333333])

### std()

In [235]:
#écart type du tableau A
A.std()

2.9297326385411577

### var()

In [237]:
#variance du tableau A
A.var()

8.583333333333334

### corrcoef: calculer des corrélations entre lignes ou colonnes

In [239]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [240]:
#matrice de corrélation
np.corrcoef(A)

array([[ 1.        , -0.56362148],
       [-0.56362148,  1.        ]])

In [241]:
#pour accéder à la valeur -0.56362148 dans la matrice de corrélation précédente
#le coefficient de correlation qui se trouve à la 1ère ligne, 2ème colonne:
np.corrcoef(A)[0,1]

-0.5636214801906779

### np.unique: compter le nombre repetitions dans notre dataset

In [243]:
#afficher A
A

array([[5, 0, 3],
       [3, 7, 9]])

In [244]:
#les éléments du tableau A et le nombre de répétitions de ces éléments
np.unique(A, return_counts=True)

(array([0, 3, 5, 7, 9]), array([1, 2, 1, 1, 1], dtype=int64))

**Exemple:**

- np.unique():

In [247]:
np.random.seed(0)

#X est un tableau de dimensions (5,5), càd 5 lignes et 5 colonnes
# et qui a des valeurs int comprises entre 0 et 10
X = np.random.randint(0, 10, [5,5])

#afficher X
X

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [248]:
#les éléments du tableau X et le nombre de répétitions de ces éléments
np.unique(X, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3], dtype=int64))

- Utiliser np.unique() avec argsort():

Classer les **2 tableaux, values** (les elements du tableau Numpy) et **counts** (les nombres de repetitions des elements du tableau Numpy) afin de trouver quelles sont les elements qui apparaissent le + souvent (ou le - souvent) dans le dataset.

In [250]:
#créer les 2 tableaux values et counts d'après le tableau X
values, counts = np.unique(X, return_counts=True)

In [251]:
#afficher le tableau values
values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [252]:
#afficher le tableau counts
counts

array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3], dtype=int64)

In [253]:
#un tableau les différents indexes qui permettent de trier counts
counts.argsort()

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8], dtype=int64)

In [254]:
#explication:
#dans le tableau counts.argsort() on a les indexes qui correspondent au tri (par ordre croissant) des valeurs du tableau counts
#le tri des éléments du tableau counts (par ordre croissant):
# 1 =< 1 < 2 =< 2 =< 2 < 3 =< 3 =< 3 < 4 =< 4
#les indexes de 1 sont: 0 et 2 dans le tableau counts
#les indexes de 2 sont: 1, 4, et 6 dans le tableau counts
#les indexes de 3 sont: 3, 5 et 9 dans le tableau counts
#les indexes de 4 sont: 7 et 8 dans le tableau counts

In [255]:
#injecter les indexes de counts.argsort() a l'intérieur du tableau values
values[counts.argsort()]

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8])

In [256]:
#explication:
#les valeurs qui apparaîssent le + souvent dans le tableau X:
# 8, puis 7, puis 9, puis 5,...etc
# 0 apparaît le - souvent, et 8 apparaît le + souvent dans le tableau X

In [257]:
#pour s'assurer des resultats: (vu précédemment)
#les éléments du tableau X et le nombre de répétitions de ces éléments
np.unique(X, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3], dtype=int64))

In [258]:
#pour rendre les resultats du tri présentables:
for i, j in zip (values[counts.argsort()], counts[counts.argsort()]):
    print(f'La valeur {i} apparait {j} fois dans le dataset.')

La valeur 0 apparait 1 fois dans le dataset.
La valeur 2 apparait 1 fois dans le dataset.
La valeur 1 apparait 2 fois dans le dataset.
La valeur 4 apparait 2 fois dans le dataset.
La valeur 6 apparait 2 fois dans le dataset.
La valeur 3 apparait 3 fois dans le dataset.
La valeur 5 apparait 3 fois dans le dataset.
La valeur 9 apparait 3 fois dans le dataset.
La valeur 7 apparait 4 fois dans le dataset.
La valeur 8 apparait 4 fois dans le dataset.


### Nan (= not a number), np.nanmean(), np.nanstd()

In [260]:
# créer une tableau (5,5) avec des valeurs aléatoires suivant une distribution normale standard  
A = np.random.randn(5, 5)  

# introductuire des valeurs manquantes (NaN) dans la matrice  
A[0, 2] = np.nan  # Remplace la valeur à la position (0, 2) par NaN  
A[4, 3] = np.nan  # Remplace la valeur à la position (4, 3) par NaN  

# afficher la matrice avec des valeurs NaN  
A

array([[ 0.44386323,  0.33367433,         nan, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,         nan, -0.38732682]])

In [261]:
#La moyenne de A
A.mean()

nan

In [262]:
#calculer la moyenne de A en ignorant les nan
np.nanmean(A)

0.010707879575141632

In [263]:
#calculer la variance de A en ignorant les nan
np.nanvar(A)

1.213857100788078

In [264]:
#calculer l'ecart type de A en ignorant les nan
np.nanstd(A)

1.1017518326683546

### Compter les NaNs dans un tableau Numpy et filtrer les NaNs avec le boolean indexing

In [266]:
#afficher A
A

array([[ 0.44386323,  0.33367433,         nan, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,         nan, -0.38732682]])

In [267]:
#l'emplacement des NaNs:
np.isnan(A)  #donne un masque

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [268]:
#nombre d'apparition des NaNs dans le tableau A
np.isnan(A).sum()   #la somme des True, dans le masque np.isnan(A)

2

In [269]:
#le rapport (et donc le %) de NaN par rapport au tableau numpy
#diviser le nombre d'apparition des NaN par le nombre d'éléments dans le tableau
np.isnan(A).sum()/A.size  

0.08

In [270]:
#remplacer les éléments NaN par 0 dans le tableau A
A[np.isnan(A)] = 0

#afficher A
A

array([[ 0.44386323,  0.33367433,  0.        , -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  0.        , -0.38732682]])

## Algèbre linéaire (partie manquante)