# Numpy

URL : https://youtu.be/NzDQTrqsxas?si=m27I7Av-n_xck9oD

## Initialiser un nd.array avec des constructeurs

In [215]:
import numpy as np

In [216]:
# créer un tableau avec 1 dimension qui contient les nbres 1, 2 et 3
A = np.array([1,2,3])

#afficher A (objet de la classe nd.array)
A

array([1, 2, 3])

### ndim, shape, size

In [218]:
#nombre de dimensions de A
A.ndim

1

In [219]:
#la forme de A
A.shape

(3,)

In [220]:
#la taille de A
A.size

3

### np.zeros

In [222]:
#tableau rempli de zeros avec 3 lignes et 2 colonnes
B = np.zeros((3, 2))

#afficher B
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [223]:
# nombre de dimensions de B
B.ndim

2

In [224]:
#forme de B
B.shape

(3, 2)

**NB:** shape est un tuple:

In [226]:
type(B.shape)

tuple

In [227]:
B.shape[0]

3

In [228]:
B.shape[1]

2

### np.ones

In [230]:
#tableau rempli de 1 avec 3 lignes et 4 colonnes
C = np.zeros((3, 4))

#afficher C
C

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [231]:
#la taille de C (nbre d'éléments du tableau C = 3x4)
C.size

12

### np.full

In [233]:
#tableau avec 2 lignes et 3 colonnes rempli de 9
D = np.full((2, 3), 9)

#afficher D
D

array([[9, 9, 9],
       [9, 9, 9]])

## np.random.randn

In [235]:
#initialiser un tableau avec des nbrs aléatoires issus de la distribution normale centrée en 0
#avec 3 lignes et 4 colonnes
np.random.randn(3, 4)

array([[-1.2928905 ,  0.7461907 ,  1.82452417,  0.79850258],
       [ 0.32420224, -0.92201826, -0.1955414 , -0.03682772],
       [-0.45777051, -0.43382264,  0.15131969, -1.35161437]])

In [236]:
#le tableau change à chaque fois qu'on exécute le code
np.random.randn(3, 4)

array([[-0.66758603,  0.31557699,  1.42307253, -0.06208412],
       [-1.36704744, -0.52535433, -1.73922469,  0.73002287],
       [-0.30373979, -0.38103185,  0.51362757,  0.18995932]])

In [237]:
#pour éviter que le tableau change à chaque fois que le code est exécuté
#on emploie la fonction seed()
np.random.seed(0)  #fixer avec le nbre 0
np.random.randn(3, 4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [238]:
np.random.seed(0)
np.random.randn(3, 4)

#le tableau ne va plus changer

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [239]:
#si on veut un autre tableau (avec des nbres aléatoires et la même taille)
np.random.seed(87678)
np.random.randn(3, 4)

array([[ 1.35931174,  0.76800742, -1.2632608 , -0.48042586],
       [-0.49189972, -0.72595927, -1.71484968,  1.24041464],
       [ 1.04295646, -0.02112269,  1.59385897,  0.08259306]])

In [240]:
np.random.seed(87678)
np.random.randn(3, 4)

#le tableau ne change pas

array([[ 1.35931174,  0.76800742, -1.2632608 , -0.48042586],
       [-0.49189972, -0.72595927, -1.71484968,  1.24041464],
       [ 1.04295646, -0.02112269,  1.59385897,  0.08259306]])

### np.eye

In [242]:
#matrice identité avec 4 lignes et 4 colonnes
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.linspace(debut, fin, nbre d'elements)

In [244]:
#tableau à 1 dim, avec 20 éléments entre 0 et 10
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### np.arange(debut, fin, nbre de pas)

In [246]:
#tableau à 1 dim, avec un pas = 1, allant de 0 à 10
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [247]:
#tableau à 1 dim, avec des élémenst allant de 0 à 10 avec un pas = 0,5
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### dtype

In [249]:
#tableau à 1 dim, avec 20 éléments entre 0 et 10
np.linspace(0, 10, 20, dtype = np.float64)  #grande précision (chaque élément occupe 64 bits en mémoire), programme lent a l'exécution

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [250]:
#tableau à 1 dim, avec 20 éléments entre 0 et 10
np.linspace(0, 10, 20, dtype = np.float16)  #(chaque élément occupe 16 bits en mémoire), plus rapide à l'exécution

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

## Manipulation des tableaux

In [252]:
#créer 2 tableaux
A = np.zeros((3,2)) #tableau de 3 lignes et 2 colonnes rempli de 0 
B = np.ones((3,2))  #tableau de 3 lignes et 2 colonnes rempli de 1

In [253]:
#afficher A
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [254]:
#afficher B
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


### np.hstack, np.vstack

In [256]:
#stacker les tableaux verticalement
C = np.vstack((A,B))

#afficher C
C

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [257]:
C.shape

(6, 2)

In [258]:
#stacker les tableaux horizontalement
D = np.hstack((A,B))

#afficher D
D

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [259]:
D.shape

(3, 4)

On peut utiliser **np.concatenate** pour avoir les memes resultats.

### np.concatenate

In [262]:
#coller les tableaux A et B de façon verticale (axis=0), semblable à np.vstack
np.concatenate((A,B), axis = 0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [263]:
#coller les tableaux A et B de façon horizontale (axis=1), semblable à np.hstack
np.concatenate((A,B), axis = 1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

**(NB: Il est preferable d'utiliser np.concatenate)**

### np.reshape

In [266]:
C

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [267]:
C.size

12

In [268]:
C.shape

(6, 2)

In [269]:
#reformer en un tableau avec la forme (3,4)
C.reshape((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [270]:
A = np.array([1, 2, 3])

#afficher A
A

array([1, 2, 3])

In [271]:
A.shape

(3,)

Pour manipuler les tableaux, on a parfois besoin de reformer un tableau avec une forme (n,) en (n,1).

"n" étant le nbre de lignes dans le tableau.

Dans ce cas, on applique le code:

In [273]:
A = np.array([1, 2, 3])

#reformer le tableau A de (3,) en (3,1)
A = A.reshape((A.shape[0], 1))  #A.shape[0]= 3

A.shape

(3, 1)

Et parfois, on a besoin de la forme (n,) du tableau plutôt que (n,1).

Dans ce cas, on applique la méthode squeeze.

In [275]:
A = A.squeeze()

In [276]:
#forme de A
A.shape

(3,)

### np.ravel()

Elle permet d'aplatir un tableau en 1 seule dimension.

In [279]:
#afficher D
D

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [280]:
#aplatir le tableau D en 1 dimension
D.ravel()

array([0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1.])

In [281]:
#forme de D.ravel()
D.ravel().shape

(12,)